version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fw-payment-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jk2etunsj44n"
s3_prefix = "fw-payment-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
