AWSTemplateFormatVersion: 2010-09-09
Description: >-
  fw-admin-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  fwadminapi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fw-admin-api
      Handler: app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 200
      Description: A Lambda function that handles the Fintwit Admin API.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonRDSFullAccess
        - AWSLambdaExecute
        - AmazonCognitoPowerUser
