AWSTemplateFormatVersion: 2010-09-09
Description: >-
  fw-analyst-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  fwanalystapi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fw-analyst-api
      Handler: 1.0/app.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 200
      Description: A Lambda function that handles the Fintwit Payment API.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonRDSFullAccess
        - AWSLambdaExecute
        - AmazonCognitoPowerUser
        - AmazonSESFullAccess
